agent:
  name: csm_tts_agent
  description: Agent that synthesizes speech from text using the CSM model.

templates:
  - template_name: InputTemplate
    class_name: InputTemplate
    attributes: {}

  - template_name: CSMTTS
    class_name: CSMTTS
    template_input: InputTemplate
    attributes:
      speaker_id: 0
      max_audio_length_ms: 10000
      device: cpu
      context: null
      sample_rate_hz: 24000

  - template_name: SaveGeneratedAudio
    class_name: AudioWriterSoundfile
    template_input: CSMTTS
    attributes:
      save_dir: "webapp/audios"


