services:
  sinapsis-speech-main: &default
    image: sinapsis-speech:base

    build:
      context: ../
      dockerfile: docker/Dockerfile
      ssh:
        - default
    environment:
      GRADIO_SHARE_APP: ${GRADIO_SHARE_APP:-false}
      PYTHONPATH: "/lib/python3.10/:/app/.venv/lib/python3.10/site-packages:"

    volumes:
      - "~/.cache/sinapsis/:/root/.cache/sinapsis"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    network_mode: "host"
