agent:
  name: voice_clone
  description: Clona una voz usando ElevenLabs a partir de un audio de referencia

templates:

- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}

- template_name: TextInput
  class_name: TextInput
  template_input: InputTemplate
  attributes:
    text: This is a test of Sinapsis Elevenlabs text-to-speech template.

- template_name: AudioReaderToBytes
  class_name: AudioReaderToBytes
  template_input: TextInput
  attributes:
    audio_file_path: artifacts/town.mp3

- template_name: ElevenLabsVoiceClone
  class_name: ElevenLabsVoiceClone
  template_input: AudioReaderToBytes
  attributes:
    name: "Clone Voice"
